# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-16 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_remove_project_percentage'),
        ('payments', '0002_auto_20200516_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundlineitem',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='fundlineitem',
            name='project',
        ),
        migrations.AddField(
            model_name='fund',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.DeleteModel(
            name='FundLineItem',
        ),
    ]
