# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-17 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200516_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='raised',
            field=models.IntegerField(default=0),
        ),
    ]
