# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-22 16:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20200517_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
