# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-22 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20200522_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
