# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-22 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20200522_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='amount',
            new_name='donation',
        ),
    ]
