# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('category', models.CharField(choices=[('ART', 'Arts'), ('C&I', 'Comics & Illustration'), ('D&T', 'Design & Tech'), ('FLM', 'Film'), ('F&C', 'Food & Craft'), ('GMS', 'Games'), ('MSC', 'Music'), ('PUB', 'Publishing'), ('UNK', 'Miscellaneous')], default='UNK', max_length=9)),
                ('description', models.TextField()),
                ('backer_story', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('goal', models.IntegerField(default=0)),
                ('end_date', models.DateField()),
            ],
        ),
    ]
