# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='project',
            name='raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ARTS', 'Arts'), ('CHAR', 'Charity'), ('FILM', 'Film'), ('FOOD', 'Food'), ('GAME', 'Games'), ('MUSE', 'Music'), ('PUBL', 'Publishing'), ('TECH', 'Technology')], default='ARTS', max_length=9),
        ),
    ]
