# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200428_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backer_story',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
