# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200428_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ARTS', 'Arts'), ('CHAR', 'Charity'), ('FILM', 'Film'), ('FOOD', 'Food'), ('GAME', 'Games'), ('MUSE', 'Music'), ('PUBL', 'Publishing'), ('TECH', 'Technology')], max_length=9),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default="{% static 'img/main_logo_small.jpg' %}", upload_to='img'),
        ),
    ]
