# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200428_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='project_end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='project_image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='project_title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='backer_story',
            new_name='what_is_in_it_for_the_backers',
        ),
    ]
