# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200428_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
