# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200428_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='what_is_in_it_for_the_backers',
            new_name='backers_story',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_title',
            new_name='title',
        ),
    ]
