# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200429_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Arts', 'ARTS'), ('Charity', 'CHAR'), ('Film', 'FILM'), ('Food', 'FOOD'), ('Games', 'GAME'), ('Music', 'MUSE'), ('Publishing', 'PUBL'), ('Technology', 'TECH')], max_length=9),
        ),
    ]
