# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200429_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ARTS', 'Arts'), ('CHAR', 'Charity'), ('FILM', 'Film'), ('FOOD', 'Food'), ('GAME', 'Games'), ('MUSE', 'Music'), ('PUBL', 'Publishing'), ('TECH', 'Technology')], max_length=9),
        ),
    ]
