# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200429_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='num_days',
            field=models.IntegerField(default=0),
        ),
    ]
