# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-16 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20200510_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='percentage',
        ),
    ]
