# Generated by Django 3.0.7 on 2020-06-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_remove_project_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Arts', 'Arts'), ('Charity', 'Charity'), ('Film', 'Film'), ('Food', 'Food'), ('Games', 'Games'), ('Music', 'Music'), ('Publishing', 'Publishing'), ('Technology', 'Technology')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Category'),
        ),
    ]
