# Generated by Django 3.0.7 on 2020-07-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20200704_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='conditions',
        ),
    ]
