# Generated by Django 3.0.7 on 2020-07-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_project_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='conditions',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
