# Generated by Django 3.0.7 on 2020-07-17 11:49

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20200712_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=projects.models.one_month_from_today),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
