# Generated by Django 3.0.8 on 2020-07-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20200725_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='No title entered', max_length=90),
            preserve_default=False,
        ),
    ]
