# Generated by Django 3.0.8 on 2020-07-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_auto_20200729_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backers_story_option1',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='backers_story_option2',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='backers_story_option3',
            field=models.TextField(max_length=5000),
        ),
    ]
