# Generated by Django 3.0.8 on 2020-07-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('projects', '0042_auto_20200729_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted_user'), related_name='projects', to='profiles.UserProfile'),
        ),
    ]
