# Generated by Django 3.0.8 on 2020-07-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20200729_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='user_profile',
        ),
    ]
