# Generated by Django 3.0.8 on 2020-07-31 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0044_auto_20200729_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted_user'), related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
