# Generated by Django 3.0.8 on 2020-07-31 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('projects', '0050_auto_20200731_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile'),
        ),
    ]
