# Generated by Django 3.0.8 on 2020-07-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('projects', '0051_auto_20200731_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted_user'), related_name='projects', to='profiles.UserProfile'),
        ),
    ]
