# Generated by Django 3.0.8 on 2020-08-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_auto_20200731_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=11),
        ),
    ]
