# Generated by Django 3.0.7 on 2020-07-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reward',
            field=models.TextField(max_length=100),
        ),
    ]
