# Generated by Django 3.0.7 on 2020-07-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200717_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_pledged',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
