# Generated by Django 3.0.8 on 2020-07-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200722_1351'),
        ('checkout', '0003_auto_20200722_2140'),
    ]

    operations = [
    ]
