# Generated by Django 3.0.8 on 2020-07-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20200725_1409'),
        ('checkout', '0005_auto_20200725_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='project_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
