# Generated by Django 3.0.8 on 2020-07-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20200725_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='project_number',
            new_name='project',
        ),
    ]
