# Generated by Django 3.0.8 on 2020-08-16 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20200802_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_pledged',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
