# Generated by Django 3.0.8 on 2020-08-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_auto_20200816_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_pledged',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
        ),
    ]
